### ISSUE TITLE
Error when using with Rush

### ISSUE THREAD

**Issue by patrickberkeley** [dfreeman/stagehand#4]
I'm trying out [Rush](rushstack.io) to manage a mono-repo that contains several ember addons and apps. When using yarn as the package manager, I get the error:

```
(node:8743) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:8743) UnhandledPromiseRejectionWarning: Error: Debug Failure.
    at CommandCoordinator.dispatchResponse (/Users/patrickberkeley/Code/PA/fe-rush/common/temp/node_modules/stagehand/lib/command-coordinator.js:54:69)
    at CommandCoordinator.<anonymous> (/Users/patrickberkeley/Code/PA/fe-rush/common/temp/node_modules/stagehand/lib/command-coordinator.js:43:29)
    at Generator.next (<anonymous>)
    at /Users/patrickberkeley/Code/PA/fe-rush/common/temp/node_modules/stagehand/lib/command-coordinator.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/patrickberkeley/Code/PA/fe-rush/common/temp/node_modules/stagehand/lib/command-coordinator.js:3:12)
    at CommandCoordinator.messageReceived (/Users/patrickberkeley/Code/PA/fe-rush/common/temp/node_modules/stagehand/lib/command-coordinator.js:40:16)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at emit (internal/child_process.js:820:12)
```

It looks like TS is somehow dying on the promise rejection in the `command-coordinator`. Any suggestions?

**Comment by patrickberkeley** [comment]
Closing because this is unrelated to stagehand. The issue was in broccoli v3.3.3 via ember-cli: https://github.com/ember-cli/ember-cli/issues/9074. The solution in our case was to use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to pin broccoli at 3.2.0.
